contact_links:
  - name: ðŸ¤” Support Question
    url: https://github.com/siemens/ix/discussions
    about: This issue tracker is not for support questions. Please post your question on the Discussions section.
