name: Deploy release docs v2

on:
  push:
    branches:
      - 'release/docs/v2'
  workflow_dispatch:
  workflow_call:

concurrency: release-preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/workflows/actions/turbo

      - name: Build
        env:
          BASE_URL: /ix/version-dev/
        run: pnpm build --cache-dir=.turbo --filter documentation

      - name: Deploy preview ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          force: false
          folder: ./packages/documentation/build
          clean-exclude: |
            version-*
            pr-preview
