name: Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      confirm_deployment:
        description: 'Please confirm deployment'
        required: true
        type: boolean
      deployment:
        description: 'Deployment instance'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    container:
      image: node:18.12.1
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v3
      - name: Check if deployment condition is fulfilled
        if: ${{ startsWith(github.ref, 'refs/heads/release/docs/v') == false || github.event.inputs.confirm_deployment == false }}
        run: |
          echo "::error ::Be sure that the workflow runs on release/docs/v* and you checked confirm"
          exit -1

      - name: Install rsync
        run: |
          apt-get update && apt-get install -y rsync

      - uses: ./.github/workflows/actions/install

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://code.siemens.com/api/v4/projects/249177/packages/npm/'
          scope: '@siemens'
          always-auth: 'true'

      - name: 'Download and link @siemens/ix-brand-theme'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READ_CSC_TOKEN }}
          NPM_TOKEN: ${{ secrets.READ_CSC_TOKEN }}
        run: |
          mkdir .tmp-brand
          cd .tmp-brand
          npm install @siemens/ix-brand-theme@2.0.0 --no-save --legacy-peer-deps
          cd ..
          cp -R ./node_modules/@siemens/ix-brand-theme ./packages/html-test-app/src/public/additional-theme

      - name: 'Build documentation for dev instance'
        uses: ./.github/workflows/actions/build
        if: ${{ github.event.inputs.deployment == 'dev' }}
        env:
          FIGMA_API_TOKEN: ${{ secrets.FIGMA_API_TOKEN }}
          BASE_URL: /version-dev/
        with:
          filter: 'documentation'
          args: '--force'

      - name: 'Build documentation for prod instance'
        uses: ./.github/workflows/actions/build
        if: ${{ github.event.inputs.deployment == 'prod' }}
        env:
          FIGMA_API_TOKEN: ${{ secrets.FIGMA_API_TOKEN }}
          BASE_URL: /
        with:
          filter: 'documentation'
          args: '--force'

      - name: Deploy production instance ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.event.inputs.deployment == 'prod' }}
        with:
          folder: ./packages/documentation/build
          clean-exclude: version-*

      - name: Deploy dev instance ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        if: ${{ github.event.inputs.deployment == 'dev' }}
        with:
          folder: ./packages/documentation/build
          target-folder: version-dev
          clean-exclude: version-*
