name: Deploy to PROD GitHub Pages

on:
  workflow_dispatch:
    inputs:
      confirm_deployment:
        description: 'Please confirm PROD deployment'
        required: true
        type: boolean

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    container:
      image: node:16.16.0
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/install
      - uses: ./.github/workflows/actions/build
        with:
          filter: '\!documentation'
      - name: 'Download @siemens/ix-brand-theme'
        run: |
          rm .yarnrc
          ROOT=$(pwd)
          echo "@siemens:registry=https://code.siemens.com/api/v4/projects/249177/packages/npm/" >> .npmrc
          echo "//code.siemens.com/api/v4/projects/249177/packages/npm/:_authToken=${{ secrets.READ_CSC_TOKEN }}" >> .npmrc
          npm install @siemens/ix-brand-theme@^1.0.0 --no-save
          rm .npmrc
          cp -R ./node_modules/@siemens/ix-brand-theme ./packages/html-test-app/src/public/additional-theme
          sed -i -e '/\"publishConfig\"/,/}/ d; /^$/d' ./packages/html-test-app/src/public/additional-theme/ix-brand-theme/package.json
          rm ./packages/html-test-app/src/public/additional-theme/ix-brand-theme/package.json-e

      - name: 'Build documentation for PROD instance'
        run: |
          yarn workspace documentation run build

      - name: 'Copy PROD documentation'
        run: |
          cp -R ./packages/documentation/build/. ./public

      - name: Deploy documentation to PROD instance
        if: ${{ github.input.confirm_deployment == true }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: ix.siemens.io
