name: Publish Beta

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'

concurrency:
  group: prepublish-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build-lib:
    uses: ./.github/workflows/build.yml
  deploy:
    needs: [build-lib]
    runs-on: ubuntu-latest
    container:
      image: node:16.16.0
      env:
        DEBIAN_FRONTEND: noninteractive
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: build-cache
        with:
          key: build-${{ runner.os }}-${{ github.sha }}
          path: |
            packages/**/dist
            packages/**/www
            packages/**/loader
            packages/**/build

      - name: Publish ix beta version to npmjs.org
        run: |
          yarn workspace @siemens/ix publish --access public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish ix-react beta version to npmjs.org
        run: |
          yarn workspace @siemens/ix-react publish --access public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish ix-aggrid beta version to npmjs.org
        run: |
          yarn workspace @siemens/ix-aggrid publish --access public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish ix-echarts beta version to npmjs.org
        run: |
          yarn workspace @siemens/ix-echarts publish --access public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish ix-angular beta version to npmjs.org
        run: |
          cd packages/angular/dist
          yarn publish --access public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
